# Wildfire Trends in the US
## By Noa


**Introduction**

First, we install and load the necessary packages.

```{r echo=T, results='hide', error=FALSE, message=FALSE, warning=FALSE}
if(!require(rio)){install.packages("rio")}
library(rio)
if(!require(dplyr)){install.packages("dplyr")}
library(dplyr)
if(!require(tidyr)){install.packages("tidyr")}
library(tidyr)
if(!require(rgdal)){install.packages("rgdal")}
library(rgdal)
if(!require(base)){install.packages("base")}
library(base)
if(!require(profvis)){install.packages("profvis")}
library(profvis)
if(!require(rnoaa)){install.packages("rnoaa")}
library(rnoaa)
if(!require(lubridate)){install.packages("lubridate")}
library(lubridate)
if(!require(sf)){install.packages("sf")}
library(sf)
if(!require(spData)){install.packages("spData")}
library(spData)
if(!require(tidyverse)){install.packages("tidyverse")}
library(tidyverse)
if(!require(data.table)){install.packages("data.table")}
library(data.table)
if(!require(ggplot2)){install.packages("ggplot2")}
library(ggplot2)
if(!require(foreach)){install.packages("foreach")}
library(foreach)
if(!require(doParallel)){install.packages("doParallel")}
library(doParallel)
if(!require(doMC)){install.packages("doMC")}
library(doMC)
```

Create directories to store data, and download the MTBS weather data.
```{r}
if(!dir.exists("Data")){
  dir.create("Data")
}
if(!dir.exists("Data/mtbs")){
  dir.create("Data/mtbs")
}
if(!file.exists('Data/mtbs/mtbs_data.csv')){
  loc <- "https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/MTBS_Fire/data/composite_data/fod_pt_shapefile/mtbs_fod_pts_data.zip"
  dest <- paste0('Data/mtbs/mtbs_data.zip')
  download.file(loc, dest)
  unzip(dest, exdir="Data/mtbs")
  unlink(dest)
  convert('Data/mtbs/mtbs_FODpoints_DD.dbf', 'Data/mtbs/mtbs_data.csv')
  #remove unnecessary files from zip
  file.remove('Data/mtbs/mtbs_FODpoints_DD.cpg')
  file.remove('Data/mtbs/mtbs_FODpoints_DD_metadata.xml')
  file.remove('Data/mtbs/mtbs_FODpoints_DD.prj')
  file.remove('Data/mtbs/mtbs_FODpoints_DD.sbn')
  file.remove('Data/mtbs/mtbs_FODpoints_DD.sbx')
  file.remove('Data/mtbs/mtbs_FODpoints_DD.shp')
  file.remove('Data/mtbs/mtbs_FODpoints_DD.shp.xml')
  file.remove('Data/mtbs/mtbs_FODpoints_DD.shx')
  file.remove('Data/mtbs/mtbs_FODpoints_DD.dbf')
}
```