# Wildfire Trends in the US: Section 2
## By Noa Mills

**The role of this script is to download the weather data files needed for each fire. This must be done in multiple rounds as data is screened for missing and faulty data. After running script 2a (remotely), transfer the firedata_2ai.csv (where i=iteration) to the local machine. Then, run this script to download new weather files to the local machine. Then, transfer the weather files to the cluster to be used in script 2c**

**I recommend using the following command to transfer to the cluster ONLY the weather files which are not currently in the remote directory, which will save time:**

*rsync -av --ignore-existing ./path/to/local/dir cruzid\@hb.ucsc.edu:~/Data/noaa/noaadata*

First, we load libraries, and scan through the data files matching the regex "firedata2a_[0123456789]+.csv" to identify which iteration we are on, and therefore, which data file we should be using.

```{r, warning=FALSE}
suppressMessages(library(rnoaa))
suppressMessages(library(dplyr))

files <- list.files(path="Data/", pattern="firedata2a_[0123456789]+.csv", recursive=FALSE)
iteration <- 1
for(file in files){
  fileval <- gsub("firedata2a_", "", file)
  fileval <- gsub(".csv", "", fileval)
  fileval <- as.integer(fileval)
  if(fileval > iteration){
    iteration <- fileval
  }
}
firedata <- read.csv(paste0("Data/firedata2a_", iteration, ".csv"), stringsAsFactors = FALSE)

```